name: Upload new image

on: 
  workflow_dispatch:
    inputs:
      language:
        required: true
        type: choice
        options:
        - ap-python
        - ap-python-xpra-base
        - flutter
        - python
        - rust
        # Add new options as dev containers for new languages are created
      version:
        required: true 
        type: string
      architecture:
        description: 'Target specific architecture'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - amd64
          - arm64

jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    
    steps:
      - name: Checking out Dockerfiles 
        # Skip the step if a specific architecture was requested and it doesn't match the matrix item
        if: ${{ inputs.architecture == '' || inputs.architecture == 'all' || inputs.architecture == matrix.arch }}
        uses: actions/checkout@v6

      - name: Docker meta
        # Skip the step if a specific architecture was requested and it doesn't match the matrix item
        if: ${{ inputs.architecture == '' || inputs.architecture == 'all' || inputs.architecture == matrix.arch }}
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: adregistry.fnal.gov/dev-containers/${{ inputs.language }}
          tags: |
            # Always tag with the image's SHA
            type=sha,prefix=

            # Enable the 'latest' tag if this is a single-architecture build
            type=raw,value=latest,enable=${{ inputs.architecture == matrix.arch }}
            
            # Append the architecture type if in a multi-architecture build
            type=raw,value=${{ inputs.version }}${{ inputs.architecture != matrix.arch && format('-{0}', matrix.arch) || '' }}

      - name: Set up Docker Buildx
        # Skip the step if a specific architecture was requested and it doesn't match the matrix item
        if: ${{ inputs.architecture == '' || inputs.architecture == 'all' || inputs.architecture == matrix.arch }}
        uses: docker/setup-buildx-action@v4

      - name: Login to AD Registry, Harbor
        # Skip the step if a specific architecture was requested and it doesn't match the matrix item
        if: ${{ inputs.architecture == '' || inputs.architecture == 'all' || inputs.architecture == matrix.arch }}
        uses: docker/login-action@v4
        with:
          registry: adregistry.fnal.gov 
          username: ${{ secrets.ADREGISTRY_USERNAME }}
          password: ${{ secrets.ADREGISTRY_SECRET }}

      - name: Build image and push to adregistry 
        # Skip the step if a specific architecture was requested and it doesn't match the matrix item
        if: ${{ inputs.architecture == '' || inputs.architecture == 'all' || inputs.architecture == matrix.arch }}
        uses: docker/build-push-action@v7 
        with:
          context: ./${{ inputs.language }}
          platforms: linux/${{ matrix.arch }}
          push: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  merge:
    # Skip the job if only 1 architecture was selected
    if: ${{ inputs.architecture == '' || inputs.architecture == 'all' }}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: adregistry.fnal.gov/dev-containers/${{ inputs.language }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ inputs.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to AD Registry
        uses: docker/login-action@v4
        with:
          registry: adregistry.fnal.gov
          username: ${{ secrets.ADREGISTRY_USERNAME }}
          password: ${{ secrets.ADREGISTRY_SECRET }}

      - name: Create Multi-Arch Manifest
        run: |
          docker buildx imagetools create \
            $(echo "${{ steps.meta.outputs.tags }}" | xargs -I {} echo "-t {}") \
            adregistry.fnal.gov/dev-containers/${{ inputs.language }}:${{ inputs.version }}-amd64 \
            adregistry.fnal.gov/dev-containers/${{ inputs.language }}:${{ inputs.version }}-arm64
